---
backend:
  name: git-gateway
  branch: main
media_folder: public/images
public_folder: /images
collections:
  - name: posts
    label: Blog Posts
    folder: src/content/posts
    create: true
    slug: "{{slug}}"
    extension: md
    format: frontmatter
    fields:
      - label: Published Date
        name: published
        widget: datetime
        date_format: YYYY-MM-DD
        time_format: false
      - label: Body
        name: body
        widget: markdown
